version: '3'
volumes:
  # volume container to provide consistent storage.
  postgres-data:

services:
  # a postgres container for providing database access.
  postgres:
    image: sameersbn/postgresql:9.4-12
    environment:
      - PGPASSWORD=]b5QH#Zw3.T\xX$X
      - DB_USER=tutorial
      - DB_PASS=hbb2ufb=Ty_RJ*dC
      - DB_NAME=tutorial
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql
