# Generated by Django 2.1.1 on 2018-09-22 10:30

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    fixtures = 'films people planets species starships transport vehicles'.split(' ')
    call_command('loaddata', *fixtures)


class Migration(migrations.Migration):
    dependencies = [
        ('starwars', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
    ]
